### ISSUE TITLE
CRAN submission?

### ISSUE THREAD

**Issue by e-kotov** [JohMast/flowmapper#1]
Hi @JohMast , are you planning to submit to CRAN at some point? We would love to use it for a vis example in https://github.com/Robinlovelace/spanishoddata

**Comment by JohMast** [comment]
Hi @e-kotov, thanks for your interest, that looks like a good fit! I will get to it in the next days.

**Comment by e-kotov** [comment]
@JohMast Awesome! CRAN is currently on holidays, and they have paused the submissions. But they should return early next week.

**Comment by e-kotov** [comment]
spotted in the newbies incoming CRAN folder 👍

**Comment by JohMast** [comment]
Yes, i guess it could take a while until its on CRAN, they probably have quite a backlog!

**Comment by e-kotov** [comment]
They do indeed. Especially since, they were on holiday for the past two weeks and the submissions were on hold.
https://r-hub.github.io/cransays/articles/dashboard.html
https://nx10.github.io/cransubs/

**Comment by JohMast** [comment]
Oh, I did not know about these dashboards! Neat! 🤓

**Comment by e-kotov** [comment]
meanwhile, here's the first plot that we put into upcoming merge in our package
![](https://raw.githubusercontent.com/Robinlovelace/spanishoddata/v1-full-support-based-on-district-level-data-only/vignettes/media/flows_plot.svg)

**Comment by JohMast** [comment]
That is great! It seems to be working as intended. Let me know if you have any issues or suggestions!

**Comment by JohMast** [comment]
on its way to CRAN!

**Comment by e-kotov** [comment]
Congrats! Have you seen our logo yet? https://github.com/Robinlovelace/spanishoddata/ We'll add `flowmapper` into Suggests and publish reproducible code to create our logo or similar plots from Spanish origin-destination data in vignettes using `flowmapper`.

Though for us going to CRAN is a bit early, a few more things to do, but we'll get there.

**Comment by JohMast** [comment]
Wow, the logo looks very nice! Thanks, and I am looking forward to seeing your package on CRAN.

**Comment by e-kotov** [comment]
@JohMast hi, I see flowmapper with od and nodes arguments is stuck in the waiting folder on CRAN. Do they want you to change something?

**Comment by JohMast** [comment]
No changes, it was just an unusually quick update so soon after release, so the CRAN team was understandably skeptical. They kindly accepted it this time :)

**Comment by e-kotov** [comment]
@JohMast great! I will remove reference to installing the from github in our vignettes. Thank you!
