### ISSUE TITLE
bundled package data

### ISSUE THREAD

**Issue by e-kotov** [JohMast/flowmapper#2]
```
checking data for non-ASCII characters ... NOTE
  Note: found 104 marked UTF-8 strings
```

from your [CRAN checks](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/flowmapper-00check.html). You might want to add something like this:
https://github.com/FlowmapBlue/flowmapblue.R/blob/c2e15d7d409527e2ea511a053b11e15ae0519258/data-raw/DATASET.R#L7

to your data prep scripts https://github.com/JohMast/flowmapper/tree/master/data-raw

**Comment by JohMast** [comment]
Thanks for the hint!
Converting from UTF-8 to UTF-8 does not seem to work for me, but `iconv(...., from = "UTF-8", to = "ASCII//TRANSLIT")` fixes it (and since it is just example data, the accents and umlauts are not necessary)

I will include it in the next version.

**Comment by JohMast** [comment]
This seems to have worked ok
