### ISSUE TITLE
Combine the colour and width legend into a single one

### ISSUE THREAD

**Issue by eugenividal** [JohMast/flowmapper#4]
Hi @JohMast, 

First of all, congratulations on the package! The visualizations are fantastic. We've been using it to plot some OD data maps of Spain for {spanishoddata} and they look amazing (see example below). However, we were wondering if it would be possible to combine the two legends (colour and width) into a single one, so that the number of trips by colour and width would be shown together. I believe this would help save space and make visualisations look neater. Thank you!

![image](https://github.com/user-attachments/assets/f9262858-be7a-4640-918a-88ea47c199d1)

**Comment by JohMast** [comment]
Good idea, something like this?
![draft](https://github.com/user-attachments/assets/839e08f3-1d6e-4074-b639-8e13b46f5c92)

I think this can be done in the way the "legend" is currently drawn, which is just as polygon, which could be broken apart into sections and filled with the appropriate color. This might be somewhat inefficient but probably not noticeably slow.

There might be a more elegant way of doing this, by creating a new type of guide, see [here](https://stackoverflow.com/a/68442175). But it will take me some time to figure out how to do this in the current ggproto system.

- [x] Option to add fill to the legend
- [ ] Implement legend as a guide

**Comment by e-kotov** [comment]
> Good idea, something like this?

That looks awesome!

**Comment by eugenividal** [comment]
@JohMast That was exactly the idea. A single legend tells you the flow volume by width and colour. Looks great!

**Comment by JohMast** [comment]
Yes, its neat! I will try to implement it this month.

**Comment by eugenividal** [comment]
Brilliant!! 👏👏👏 Thanks a lot @JohMast

**Comment by JohMast** [comment]
I added the argument `legend_gradient` which, if `TRUE`, should produce such a legend. Would be great if you could test it @eugenividal

**Comment by e-kotov** [comment]
<img width="573" alt="Screenshot 2024-09-09 at 09 56 06" src="https://github.com/user-attachments/assets/4f8f07df-f144-4542-ba76-8bbcf50fb5c3">

<img width="539" alt="Screenshot 2024-09-09 at 09 57 42" src="https://github.com/user-attachments/assets/103cb061-fd03-4bbf-9a72-7269803200cd">

works very well!

**Comment by e-kotov** [comment]
CRAN is going to complain again if you push this update too soon, maybe wait till end of this week. I think the note on "x days since last version" disappears after about a week from the last update.

**Comment by JohMast** [comment]
Yes, I don't want to bother them too much, and would aim to make the next cran release at the beginning of October. I hope that works for you.

**Comment by e-kotov** [comment]
Sure, I can update the vignette on static flow maps any time after that.

**Comment by eugenividal** [comment]
Wow, so fast! Thanks @JohMast. It looks great 🤩. Thanks @e-kotov for testing! I am closing the issue if that is Ok.
