### ISSUE TITLE
package logo

### ISSUE THREAD

**Issue by e-kotov** [JohMast/flowmapper#5]
Hi, I'm currently at [EuroCarto 2024](https://eurocarto2024.org/) conference. I will be promoting our https://github.com/rOpenSpain/spanishoddata/ + https://github.com/FlowmapBlue/flowmapblue.R + putting a link to your package on my slides too. For the first two packages we have hex sticker logos. If you have time to think of a logo for `{flowmapper}`, I'd be glad to include it too. You can find examples here:
- https://github.com/rOpenSpain/spanishoddata/blob/main/tools/generate_package_logo.R
- https://github.com/FlowmapBlue/flowmapblue.R/blob/master/tools/generate_package_logo.R

My presentation is on Wednesday, I will have time to adjust the slides on Tuesday evening at the latest.

**Comment by JohMast** [comment]
Cool idea 🤓 first time i made a hexagon with this package. If you want to include it, i'd be happy. Thanks, and enjoy the conference!
![hex](https://github.com/user-attachments/assets/c23a67d4-f62b-4571-9f7c-217b13744746)

**Comment by e-kotov** [comment]
Hmmm, I see new logo. Too late, I showed the old one today)

**Comment by JohMast** [comment]
Haha yeah, i am still experimenting 🤓 Thanks for sharing!
