### ISSUE TITLE
clusters from k_nodes

### ISSUE THREAD

**Issue by pedreirajr** [JohMast/flowmapper#6]
Hi @JohMast,

First of all, congratulations on the outstanding package you've developed! I'm already using it in my Transport Planning classes here in Brazil, and it has been incredibly valuable.

The functionality to cluster nodes and reduce clutter on maps with the `k_nodes` parameter from the `add_flowmap` function is particularly insightful. However, I was wondering if it’s possible to retrieve a list of clusters along with the nodes assigned to each cluster. This feature would be helpful for visualizing and explaining which regions were aggregated in the clustering process.

Is there currently a way to achieve this using the existing functions in the package?

Looking forward to your response.

Cheers,
Jorge

**Comment by JohMast** [comment]
Hi Jorge, I am glad you are finding the package useful! 

This functionality is not currently provided, but it should be easy to find a way that works for you. The cluster assignment is done by `add_flowmap `calling `hca_flowdat ` . You can now call this function directly with the argument return_cluster_assignment, which will give you a tibble with cluster assignments for the chosen k.

`flowmapper:::hca_flowdat(testdata, k=4, return_cluster_assignment = T)`

Is this a useful solution for you?

**Comment by pedreirajr** [comment]
Thank you very much, @JohMast, for your detailed response. However, I am encountering the following error when trying to execute the function:

`Error: 'hca_flowdat' is not an exported object from 'namespace:flowmapper'.`

This issue occurs both when I install the CRAN version and the development version using: `devtools::install_github("https://github.com/JohMast/flowmapper")`

Additionally, when I check the help for the `hca_flowdat` function, it seems that the parameter `return_cluster_assignment` is not available:
![image](https://github.com/user-attachments/assets/117dc211-a0ce-4207-ad48-041aaa9a97c6)


Any idea what might be happening? Thank you again for your assistance!

**Comment by JohMast** [comment]
Hi @pedreirajr 
Thanks for the detailed description. The CRAN version does not have this functionality yet, so it is not surprising. However, it is implemented on the development version. I tested this on a separate system and was able to pass the `return_cluster_assignment` argument. So I suspect the issue is with the installation. 

Could you try to use `devtools::install_github("https://github.com/JohMast/flowmapper")`, and check if the build works out fine?
Ideally, you can use `remove.packages("flowmapper")` beforehand to remove the previous version.

**Comment by pedreirajr** [comment]
Hi @JohMast ,

Thank you again for your support and patience!
I followed your suggestion to uninstall the package using  `remove.packages("flowmapper")` and reinstalled it with `devtools::install_github("https://github.com/JohMast/flowmapper")`. The help documentation for the function now appears updated, as shown in the image below:

![image](https://github.com/user-attachments/assets/b8720aa9-60c2-4943-aaf3-90dc7a66bbbf)

However, I’m still encountering the same error when trying to execute the function. I used the toy dataset provided in the package's README:

`testdata <-
data.frame(
   id_a = c("X1","X2","X3","X3","X1","X2","X2"),
   id_b = c("X5","X4","X1","X5","X4","X5","X3"),
   xa = c(2,14,10,10,2,14,14),
   ya = c(6,10,9,9,6,10,10),
   xb = c(10,4,2,10,4,10,10),
   yb = c(4,10,6,4,10,4,9),
   flow_ab = c(1,2,3,3,1,1,4),
   flow_ba = c(2,3,2,5,2,1,5)
)`

After running the `hca_flowdat` function:
`clusters <- flowmapper::hca_flowdat(test_data, k=2, return_cluster_assignment = T)`

unfortunately, the same error was returned:
`Error: 'hca_flowdat' is not an exported object from 'namespace:flowmapper'`

Perhaps there is an issue with my setup or configuration.

Cheers,
Jorge

**Comment by JohMast** [comment]
Hi @pedreirajr 
no worries, I think your setup is fine.  `hca_flowdat `is just not exported as a public function (since this is not a core functionality and want to keep the package simple. If you think this is inconvenient, I can also change this).
Anyway, for now, it should work only if you call the function with triple colons as follows:
` clusters <- flowmapper:::hca_flowdat(test_data, k=2, return_cluster_assignment = T)`

**Comment by pedreirajr** [comment]
Hi @JohMast,

Apologies for not realizing earlier that a third colon was required. It’s working perfectly now, thank you!

I have a suggestion for when the function is incorporated into CRAN: it would be great to allow OD data input similar to the `od` parameter in `add_flowmap`. This format seems more common and straightforward to generate, especially when working with trip data from Origin-Destination surveys using simple `group_by` and `summarize` operations.

Cheers,
Jorge

**Comment by JohMast** [comment]
Wonderful, and thanks for the suggestion. I will think on how to best implement this.
